[package]
name = "proxy-crab-mgr"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-compression.workspace = true
async-trait.workspace = true
axum.workspace = true
base64.workspace = true
bytes.workspace = true
futures.workspace = true
getrandom.workspace = true
http-body-util.workspace = true
proxy-crab-mitm = { path = "../proxy-crab-mitm" }
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
subtle.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
url.workspace = true
time = { workspace = true, features = ["formatting"] }

[dev-dependencies]
brotli.workspace = true
flate2.workspace = true
tempfile = "3"
zstd.workspace = true
tower.workspace = true
