[package]
name = "proxy-crab-mgr"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-compression.workspace = true
async-trait.workspace = true
axum.workspace = true
base64.workspace = true
bytes.workspace = true
futures.workspace = true
proxy-crab-mitm = { path = "../proxy-crab-mitm" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

[dev-dependencies]
brotli.workspace = true
flate2.workspace = true
tempfile = "3"
zstd.workspace = true
tower.workspace = true
